version: "3.9"
services:

  database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - ipongnetwork

  migration:
    build:
      context: ./backend/prisma
      dockerfile: Dockerfile
    image: migration_ipong:latest
    env_file:
      - ./.env
    networks:
      - ipongnetwork
    depends_on:
      - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_ipong:latest
    networks:
      - ipongnetwork
    depends_on:
      - migration
    ports:
      - 3000:3000
    env_file:
      - ./.env
    init: true
    restart: always
   
  front:
    container_name: front_ipong
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - front:/app/build
    ports:
      - 5173:5173
    networks:
      - ipongnetwork


volumes: 
  front:
  database:

networks:
  ipongnetwork:
    driver: bridge