version: '3.9'
services:

  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: ipong
      POSTGRES_PASSWORD: ipong
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    depends_on:
      - backend
    
networks:
  default:
    