services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: ipong
      POSTGRES_PASSWORD: ipong
    restart: on-failure