export const Suggestions = [
  "Hello",
  "Hi",
  "Hey",
  "Howdy",
  "Greetings",
  "Salutations",
  "Good morning",
  "Good afternoon",
  "Good evening",
  "How are you?",
  "What's up?",
  "How's it going?",
  "Nice to meet you",
  "Pleasure to meet you",
  "Long time no see",
  "Goodbye",
  "Farewell",
  "Take care",
  "See you later",
  "Catch you later",
  "Have a good day",
  "Have a great day",
  "Best wishes",
  "Cheers",
  "Good night",
  "Sweet dreams",
  "Talk to you soon",
  "See you soon",
  "Thanks",
  "Thank you",
  "Many thanks",
  "Much appreciated",
  "Thanks a lot",
  "Thank you very much",
  "You're welcome",
  "No problem",
  "No worries",
  "Don't mention it",
  "My pleasure",
  "Anytime",
  "Congratulations",
  "Well done",
  "Good job",
  "Fantastic",
  "Excellent",
  "Amazing",
  "Great work",
  "Keep it up",
  "Best of luck",
  "All the best",
  "Break a leg",
  "Fingers crossed",
  "Happy birthday",
  "Merry Christmas",
  "Happy New Year",
  "Happy holidays",
  "Season's greetings",
  "Happy Easter",
  "Happy Thanksgiving",
  "Happy Halloween",
  "Nice work",
  "Impressive",
  "Well played",
  "Good effort",
  "Well done",
  "Nice try",
  "Almost there",
  "Better luck next time",
  "Hard luck",
  "I apologize",
  "Sorry",
  "My apologies",
  "I didn't mean to",
  "Forgive me",
  "I'm sorry",
  "Excuse me",
  "Pardon me",
  "Allow me",
  "Excuse my interruption",
  "Sorry to bother you",
  "Could you please",
  "Would you mind",
  "Can I ask",
  "May I",
  "Could I",
  "Would it be possible",
  "Do you mind",
  "Would you kindly",
  "Can you help me",
  "I need assistance",
  "Can you assist me",
  "I need help",
  "Help me please",
  "Please assist",
  "I would like",
  "I need",
  "I want",
  "Can I have",
  "Could I get",
  "May I have",
  "Do you have",
  "Is there any",
  "Where can I find",
  "What is",
  "How do I",
  "When is",
  "Why is",
  "Who is",
  "What are",
  "How are",
  "When are",
  "Why are",
  "Who are",
  "What was",
  "How was",
  "When was",
  "Why was",
  "Who was",
  "What will",
  "How will",
  "When will",
  "Why will",
  "Who will",
  "What should",
  "How should",
  "When should",
  "Why should",
  "Who should",
  "What could",
  "How could",
  "When could",
  "Why could",
  "Who could",
  "What might",
  "How might",
  "When might",
  "Why might",
  "Who might",
  "What if",
  "How if",
  "When if",
  "Why if",
  "Who if",
  "What about",
  "How about",
  "When about",
  "Why about",
  "Who about",
  "What do you think",
  "How do you feel",
  "When do you think",
  "Why do you think",
  "Who do you think",
  "What are your thoughts",
  "How are you feeling",
  "When are you available",
  "Why do you feel",
  "Who do you suggest",
  "What can we do",
  "How can we help",
  "When can we meet",
  "Why should we",
  "Who should we contact",
  "What did you mean",
  "How did you know",
  "When did you realize",
  "Why did you choose",
  "Who did you ask",
  "Salam",
  "Salamu Alaykum",
  "Slamtek",
  "Labas",
  "Bslama",
  "Merhba",
  "Sabah lkhir",
  "Msa lkhir",
  "L3achiya lkhir",
  "Kif dayer?",
  "Wach hadak?",
  "Kifach?",
  "Sbah lkhir",
  "L3achiya bsa7tek",
  "Mre7ba bsa7tek",
  "Lila, ghrbt 3lik",
  "Bslama",
  "Saha",
  "Nsma3 fik",
  "Sb7an Allah",
  "Bisaha",
  "Nhar lkhir",
  "Jaya lkhir",
  "Rani m3ak",
  "Nhar jdid",
  "Mabrouk",
  "Mabrouk 3lik",
  "Baraka mn Chabab",
  "Choukrane",
  "Choukran bzaaf",
  "Choukran bzaf",
  "Afek",
  "Ma fhemtch",
  "Ma problèm",
  "Ma3ndich mouchkil",
  "Lbass",
  "Ana mr7ba bik",
  "Achno radi",
  "3afak",
  "3afak",
  "3afak",
  "9abel man",
  "3afak",
  "9a3edni",
  "3afak",
  "Bghit",
  "Bghit",
  "Bghit",
  "Bghit",
  "Wach 3ndk",
  "Fin ghadi nla9a",
  "Achno",
  "Kifach",
  "Mata",
  "Lih",
  "Ili",
  "Chkoun",
  "Wach kan",
  "3lach kan",
  "Man",
  "Wach gha",
  "Chkoun gha",
  "Chkoun",
  "Ila kan",
  "Kifach kan",
  "Mata kan",
  "3lach kan",
  "Man kan",
  "Kan ch7al",
  "Kifach lw9t",
  "Mata lw9t",
  "3lach lw9t",
  "Man lw9t",
  "Kan lwa9t",
  "3lach lwa9t",
  "Man lwa9t",
  "Chkoun lwa9t",
  "Ila kan",
  "Kifach kan",
  "Mata kan",
  "3lach kan",
  "Man kan",
  "Kan 3ajbni",
  "Kifach 3ajbni",
  "Mata 3ajbni",
  "3lach 3ajbni",
  "Man 3ajbni",
  "Wach 3andi",
  "Kifach 3andi",
  "Mata 3andi",
  "3lach 3andi",
  "Man 3andi",
  "Wach kayn",
  "Kifach kayn",
  "Mata kayn",
  "3lach kayn",
  "Man kayn",
  "Wach drti",
  "Kifach drti",
  "Mata drti",
  "3lach drti",
  "Man drti",
  "Wach ghadi",
  "Kifach ghadi",
  "Mata ghadi",
  "3lach ghadi",
  "Man ghadi",
  "Wach l7al",
  "Kifach l7al",
  "Mata l7al",
  "3lach l7al",
  "Man l7al",
  "Wach kat3rfi",
  "Kifach tkon",
  "Mata tkon",
  "3lach tkon",
  "Man tkon",
  "Wach fik",
  "Kifach tkoun",
  "Mata tkoun",
  "3lach tkoun",
  "Man tkoun",
  "Wach rai7a",
  "Kifach rai7a",
  "Mata rai7a",
  "3lach rai7a",
  "Man rai7a",
  "Wach ghadi",
  "Kifach ghadi",
  "Mata ghadi",
  "3lach ghadi",
  "Man ghadi",
  "Wach ghadi tkoun",
  "Kifach ghadi n3rfou",
  "Mata ghadi nla9a",
  "3lach ghadi",
  "Man ghadi",
  "Wach ghadi tfahmi",
  "Kifach ghadi t3rfo",
  "Mata ghadi t3rfo",
  "3lach ghadi",
  "Man ghadi",
];
