export  const Suggestions = [
    "Hello", "Hi", "Hey", "Howdy", "Greetings", "Salutations", "Good morning",
    "Good afternoon", "Good evening", "How are you?", "What's up?", "How's it going?",
    "Nice to meet you", "Pleasure to meet you", "Long time no see", "Goodbye", "Farewell",
    "Take care", "See you later", "Catch you later", "Have a good day", "Have a great day",
    "Best wishes", "Cheers", "Good night", "Sweet dreams", "Talk to you soon", "See you soon",
    "Thanks", "Thank you", "Many thanks", "Much appreciated", "Thanks a lot", "Thank you very much",
    "You're welcome", "No problem", "No worries", "Don't mention it", "My pleasure", "Anytime",
    "Congratulations", "Well done", "Good job", "Fantastic", "Excellent", "Amazing", "Great work",
    "Keep it up", "Best of luck", "All the best", "Break a leg", "Fingers crossed", "Happy birthday",
    "Merry Christmas", "Happy New Year", "Happy holidays", "Season's greetings", "Happy Easter",
    "Happy Thanksgiving", "Happy Halloween", "Nice work", "Impressive", "Well played",
    "Good effort", "Well done", "Nice try", "Almost there", "Better luck next time", "Hard luck",
    "I apologize", "Sorry", "My apologies", "I didn't mean to", "Forgive me", "I'm sorry",
    "Excuse me", "Pardon me", "Allow me", "Excuse my interruption", "Sorry to bother you",
    "Could you please", "Would you mind", "Can I ask", "May I", "Could I", "Would it be possible",
    "Do you mind", "Would you kindly", "Can you help me", "I need assistance", "Can you assist me",
    "I need help", "Help me please", "Please assist", "I would like", "I need", "I want",
    "Can I have", "Could I get", "May I have", "Do you have", "Is there any", "Where can I find",
    "What is", "How do I", "When is", "Why is", "Who is", "What are", "How are", "When are",
    "Why are", "Who are", "What was", "How was", "When was", "Why was", "Who was", "What will",
    "How will", "When will", "Why will", "Who will", "What should", "How should", "When should",
    "Why should", "Who should", "What could", "How could", "When could", "Why could", "Who could",
    "What might", "How might", "When might", "Why might", "Who might", "What if", "How if",
    "When if", "Why if", "Who if", "What about", "How about", "When about", "Why about", "Who about",
    "What do you think", "How do you feel", "When do you think", "Why do you think", "Who do you think",
    "What are your thoughts", "How are you feeling", "When are you available", "Why do you feel",
    "Who do you suggest", "What can we do", "How can we help", "When can we meet", "Why should we",
    "Who should we contact", "What did you mean", "How did you know", "When did you realize", 
    "Why did you choose", "Who did you ask"
  ];