export const GAME_SETTINGS = {
  /* Game Play Settings */
  GAME_WIDTH: 800,
  GAME_HEIGHT: 500,
  FRAME_PER_SECONDS: 60,
  GAME_TARGET: 10,

  /* Players Settings */
  PLAYERS_WIDTH_PERCENTAGE: 3,
  PLAYERS_HEIGHT_PERCENTAGE: 20,
  FRACTION_FOR_SPEED: 0.05,

  /* Ball Settings */
  BALL_SIZE_PERCENTAGE: 2.5,
  BALL_SPEED_FACTOR: 0.015,
  BALL_VELOCITY: 5,
};
