export const USER_XP_REWARDS = {
  DID_NOT_LEAVE: 10,
  OTHER_PLAYER_LEFT_WIN: 30,

  WINNER_SM_XP_AMOUNT: 50,
  WINNER_LARGE_XP_AMOUNT: 80,
  WINNER_X_LARGE_XP_AMOUNT: 110,

  LOSER_CASE_LEFT_GAME: 0,
  LOSER_S_XP_AMOUNT: 15,
  LOSER_M_XP_AMOUNT: 30,
  LOSER_L_XP_AMOUNT: 50,
};

export const PUNISHMENT_USER_XP = {
  LEAVE_GAME: -25,
};

export const USER_WALLET_REWARDS = {
  WALLET_NOT_FINISHED_GAME: 3,
  WALLET_DEFAULT_AMOUNT: 7,
  WALLET_WINNER_S_AMOUNT: 14,
  WALLET_WINNER_M_AMOUNT: 23,
  WALLET_WINNER_L_AMOUNT: 35,

  WALLET_LOSER_DEFAULT_AMOUNT: 0,
  WALLET_LOSER_S_AMOUNT: 5,
  WALLET_LOSER_M_AMOUNT: 10,
  WALLET_LOSER_L_AMOUNT: 15,
};
