import React from "react";

const columns = [
  { name: "BLOCKED FRIEND", uid: "blockedfriend", sortable: true },
  { name: "UNBLOCK", uid: "unblock", sortable: false },
];

const statusOptions = [
  { name: "Win", uid: "win" },
  { name: "Loss", uid: "loss" },
  { name: "Draw", uid: "draw" },
];

const matches = [
  {
    id: 1,
    versus: "Ahmed Mahmoud",
    vbucks: "+160 V-BUCKS",
    result: "win",
    date: "2023-05-01 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player1",
    email: "player1@example.com",
    username: "Ahmed21",
  },
  {
    id: 2,
    versus: "Mohammed Ali",
    vbucks: "+50 V-BUCKS",
    result: "loss",
    date: "2023-05-02 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player2",
    email: "player2@example.com",
    username: "Mohammed95",
  },
  {
    id: 3,
    versus: "Abdul Rahman Suleiman",
    vbucks: "+75 V-BUCKS",
    result: "draw",
    date: "2023-05-03 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player3",
    email: "player3@example.com",
    username: "AbdulRahman77",
  },
  {
    id: 4,
    versus: "Youssef Mohamed",
    vbucks: "+200 V-BUCKS",
    result: "win",
    date: "2023-05-04 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player4",
    email: "player4@example.com",
    username: "Youssef_gamer",
  },
  {
    id: 5,
    versus: "Amira El Sayed",
    vbucks: "+150 V-BUCKS",
    result: "win",
    date: "2023-05-05 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player5",
    email: "player5@example.com",
    username: "AmiraTheWinner",
  },
  {
    id: 6,
    versus: "Khaled Ahmed",
    vbucks: "+180 V-BUCKS",
    result: "loss",
    date: "2023-05-06 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player6",
    email: "player6@example.com",
    username: "KhaledGaming",
  },
  {
    id: 7,
    versus: "Fatima Ali",
    vbucks: "+220 V-BUCKS",
    result: "win",
    date: "2023-05-07 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player7",
    email: "player7@example.com",
    username: "FatimaGamer",
  },
  {
    id: 8,
    versus: "Omar Hassan",
    vbucks: "+90 V-BUCKS",
    result: "draw",
    date: "2023-05-08 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player8",
    email: "player8@example.com",
    username: "OmarGamer77",
  },
  {
    id: 9,
    versus: "Sara Abdelaziz",
    vbucks: "+110 V-BUCKS",
    result: "win",
    date: "2023-05-09 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player9",
    email: "player9@example.com",
    username: "SaraTheGamer",
  },
  {
    id: 10,
    versus: "Ali Hassan",
    vbucks: "+130 V-BUCKS",
    result: "loss",
    date: "2023-05-10 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player10",
    email: "player10@example.com",
    username: "AliHassanGaming",
  },
  {
    id: 11,
    versus: "Noura Mohamed",
    vbucks: "+180 V-BUCKS",
    result: "draw",
    date: "2023-05-11 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player11",
    email: "player11@example.com",
    username: "NouraGamer",
  },
  {
    id: 12,
    versus: "Ahmed Kamal",
    vbucks: "+250 V-BUCKS",
    result: "win",
    date: "2023-05-12 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player12",
    email: "player12@example.com",
    username: "KamalGaming",
  },
  {
    id: 13,
    versus: "Hassan Ibrahim",
    vbucks: "+300 V-BUCKS",
    result: "loss",
    date: "2023-05-13 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player13",
    email: "player13@example.com",
    username: "HassanGamer",
  },
  {
    id: 14,
    versus: "Reem Mahmoud",
    vbucks: "+270 V-BUCKS",
    result: "draw",
    date: "2023-05-14 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player14",
    email: "player14@example.com",
    username: "ReemTheGamer",
  },
  {
    id: 15,
    versus: "Yassin Ali",
    vbucks: "+190 V-BUCKS",
    result: "win",
    date: "2023-05-15 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player15",
    email: "player15@example.com",
    username: "YassinGaming",
  },
  {
    id: 16,
    versus: "Salma Hassan",
    vbucks: "+140 V-BUCKS",
    result: "loss",
    date: "2023-05-16 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player16",
    email: "player16@example.com",
    username: "SalmaTheWinner",
  },
  {
    id: 17,
    versus: "Aliya Abdelrahman",
    vbucks: "+100 V-BUCKS",
    result: "draw",
    date: "2023-05-17 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player17",
    email: "player17@example.com",
    username: "AliyaGamer",
  },
  {
    id: 18,
    versus: "Omar Youssef",
    vbucks: "+80 V-BUCKS",
    result: "win",
    date: "2023-05-18 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player18",
    email: "player18@example.com",
    username: "OmarYoussefGamer",
  },
  {
    id: 19,
    versus: "Mona Hassan",
    vbucks: "+220 V-BUCKS",
    result: "loss",
    date: "2023-05-19 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player19",
    email: "player19@example.com",
    username: "MonaTheGamer",
  },
  {
    id: 20,
    versus: "Karim Ali",
    vbucks: "+250 V-BUCKS",
    result: "win",
    date: "2023-05-20 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player20",
    email: "player20@example.com",
    username: "KarimTheWinner",
  },
  {
    id: 21,
    versus: "Nadia Ahmed",
    vbucks: "+180 V-BUCKS",
    result: "loss",
    date: "2023-05-21 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player21",
    email: "player21@example.com",
    username: "NadiaGaming",
  },
  {
    id: 22,
    versus: "Aya Mohamed",
    vbucks: "+300 V-BUCKS",
    result: "draw",
    date: "2023-05-22 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player22",
    email: "player22@example.com",
    username: "AyaTheGamer",
  },
  {
    id: 23,
    versus: "Tarek Ali",
    vbucks: "+270 V-BUCKS",
    result: "win",
    date: "2023-05-23 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player23",
    email: "player23@example.com",
    username: "TarekGaming",
  },
  {
    id: 24,
    versus: "Fadia Hassan",
    vbucks: "+150 V-BUCKS",
    result: "loss",
    date: "2023-05-24 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player24",
    email: "player24@example.com",
    username: "FadiaTheWinner",
  },
  {
    id: 25,
    versus: "Saif Ali",
    vbucks: "+120 V-BUCKS",
    result: "draw",
    date: "2023-05-25 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player25",
    email: "player25@example.com",
    username: "SaifGamer",
  },
  {
    id: 26,
    versus: "Laila Mohamed",
    vbucks: "+200 V-BUCKS",
    result: "win",
    date: "2023-05-26 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player26",
    email: "player26@example.com",
    username: "LailaGamer",
  },
  {
    id: 27,
    versus: "Amr Hassan",
    vbucks: "+100 V-BUCKS",
    result: "loss",
    date: "2023-05-27 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player27",
    email: "player27@example.com",
    username: "AmrTheWinner",
  },
  {
    id: 28,
    versus: "Mariam Ali",
    vbucks: "+190 V-BUCKS",
    result: "draw",
    date: "2023-05-28 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player28",
    email: "player28@example.com",
    username: "MariamGamer",
  },
  {
    id: 29,
    versus: "Mostafa Ahmed",
    vbucks: "+220 V-BUCKS",
    result: "win",
    date: "2023-05-29 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player29",
    email: "player29@example.com",
    username: "MostafaGamer",
  },
  {
    id: 30,
    versus: "Nour Hassan",
    vbucks: "+300 V-BUCKS",
    result: "loss",
    date: "2023-05-30 14:10:02",
    avatar: "https://i.pravatar.cc/150?u=player30",
    email: "player30@example.com",
    username: "NourGamer",
  },
];

  

export { columns, matches, statusOptions };
