import React from "react";

export const users = [
  {
    id: 1,
    name: "Ali Ahmed",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    email: "ali.ahmed@example.com",
  },
  {
    id: 2,
    name: "Fatima Zahra",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    email: "fatima.zahra@example.com",
  },
  {
    id: 3,
    name: "Omar Khaled",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    email: "omar.khaled@example.com",
  },
  {
    id: 4,
    name: "Layla Youssef",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    email: "layla.youssef@example.com",
  },
  {
    id: 5,
    name: "Hassan Mohammad",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    email: "hassan.mohammad@example.com",
  },
  {
    id: 6,
    name: "Aisha Ali",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    email: "aisha.ali@example.com",
    status: "Active",
  },
  {
    id: 7,
    name: "Ibrahim Jamil",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "27",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    email: "ibrahim.jamil@example.com",
  },
  {
    id: 8,
    name: "Dana Farah",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "31",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    email: "dana.farah@example.com",
  },
  {
    id: 9,
    name: "Zainab Hadi",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "33",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    email: "zainab.hadi@example.com",
  },
  {
    id: 10,
    name: "Youssef Amine",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    email: "youssef.amine@example.com",
  },
  {
    id: 11,
    name: "Mustafa Tamer",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    email: "mustafa.tamer@example.com",
  },
  {
    id: 12,
    name: "Huda Rashid",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    email: "huda.rashid@example.com",
  },
  {
    id: 13,
    name: "Salma Rami",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    email: "salma.rami@example.com",
  },
  {
    id: 14,
    name: "Karim Hassan",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    email: "karim.hassan@example.com",
  },
  {
    id: 15,
    name: "Sami Naji",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    email: "sami.naji@example.com",
  },
  {
    id: 16,
    name: "Amal Omar",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    email: "amal.omar@example.com",
  },
  {
    id: 17,
    name: "Mohammed Saeed",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    email: "mohammed.saeed@example.com",
  },
  {
    id: 18,
    name: "Noor Alia",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    email: "noor.alia@example.com",
  },
  {
    id: 19,
    name: "Nabil Fouad",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    email: "nabil.fouad@example.com",
  },
  {
    id: 20,
    name: "Rania Karim",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    email: "rania.karim@example.com",
  },
  {
    id: 21,
    name: "Khalid Adnan",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "40",
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    email: "khalid.adnan@example.com",
  },
  {
    id: 22,
    name: "Layla Omar",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    email: "layla.omar@example.com",
  },
  {
    id: 23,
    name: "Omar Hassan",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "27",
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    email: "omar.hassan@example.com",
  },
  {
    id: 24,
    name: "Aisha Farah",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "31",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    email: "aisha.farah@example.com",
  },
  {
    id: 25,
    name: "Youssef Ali",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    email: "youssef.ali@example.com",
  },
  {
    id: 26,
    name: "Dana Khaled",
    role: "P. Manager",
    team: "Management",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    email: "dana.khaled@example.com",
    status: "Active",
  },
  {
    id: 27,
    name: "Hassan Youssef",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "30",
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    email: "hassan.youssef@example.com",
  },
  {
    id: 28,
    name: "Fatima Omar",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "35",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    email: "fatima.omar@example.com",
  },
  {
    id: 29,
    name: "Salim Rami",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "37",
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    email: "salim.rami@example.com",
  },
  {
    id: 30,
    name: "Nour Amine",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "32",
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    email: "nour.amine@example.com",
  },
  {
    id: 31,
    name: "Zayn Mustafa",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "25",
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    email: "zayn.mustafa@example.com",
  },
  {
    id: 32,
    name: "Amira Rashid",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "27",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    email: "amira.rashid@example.com",
  },
  {
    id: 33,
    name: "Tariq Salim",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "40",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    email: "tariq.salim@example.com",
  },
  {
    id: 34,
    name: "Nadia Karim",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    email: "nadia.karim@example.com",
  },
  {
    id: 35,
    name: "Bilal Sami",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    email: "bilal.sami@example.com",
  },
  {
    id: 36,
    name: "Rana Noor",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "33",
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    email: "rana.noor@example.com",
  },
  {
    id: 37,
    name: "Hadi Khalid",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "26",
    avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    email: "hadi.khalid@example.com",
  },
  {
    id: 38,
    name: "Mona Saeed",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/women/38.jpg",
    email: "mona.saeed@example.com",
  },
  {
    id: 39,
    name: "Adel Naji",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "34",
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    email: "adel.naji@example.com",
  },
  {
    id: 40,
    name: "Sara Karim",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "24",
    avatar: "https://randomuser.me/api/portraits/women/40.jpg",
    email: "sara.karim@example.com",
  },
  {
    id: 41,
    name: "Zaid Ali",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "38",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    email: "zaid.ali@example.com",
  },
  {
    id: 42,
    name: "Leila Ahmed",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "30",
    avatar: "https://randomuser.me/api/portraits/women/42.jpg",
    email: "leila.ahmed@example.com",
  },
  {
    id: 43,
    name: "Ayman Khalid",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "26",
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    email: "ayman.khalid@example.com",
  },
  {
    id: 44,
    name: "Nour Jamil",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "29",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    email: "nour.jamil@example.com",
  },
  {
    id: 45,
    name: "Karim Tamer",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "32",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    email: "karim.tamer@example.com",
  },
  {
    id: 46,
    name: "Zahra Khaled",
    role: "P. Manager",
    team: "Management",
    age: "28",
    avatar: "https://randomuser.me/api/portraits/women/46.jpg",
    email: "zahra.khaled@example.com",
    status: "Active",
  },
  {
    id: 47,
    name: "Mounir Hadi",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "34",
    avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    email: "mounir.hadi@example.com",
  },
  {
    id: 48,
    name: "Sana Omar",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "37",
    avatar: "https://randomuser.me/api/portraits/women/48.jpg",
    email: "sana.omar@example.com",
  },
  {
    id: 49,
    name: "Rami Salim",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "36",
    avatar: "https://randomuser.me/api/portraits/men/49.jpg",
    email: "rami.salim@example.com",
  },
  {
    id: 50,
    name: "Samia Amine",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "33",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
    email: "samia.amine@example.com",
  },
];
